name: Mirror repository
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pixta-dev/repository-mirroring-action@v1.0.2
      with:
        # Target url
        target_repo_url: ssh://github.com/GeekTech-mirror/qt-cybercraft.git
